- .stylelintrc
- packages/css-normalize/package.json
- packages/css-normalize/src/css-normalize.tsx
- packages/css-normalize/src/index.ts
- packages/css-normalize/tsconfig.json
Create CSS normalize component
> feat(css-normalize): create CSS normalize component

- .github/CODEOWNERS
Reference: https://docs.github.com/es/github/creating-cloning-and-archiving-repositories/about-code-owners
> chore(codeowners): configure codeowners

- packages/button/src/ButtonText.tsx
- packages/button/src/index.ts
- packages/button/stories/TextButton.stories.tsx
- packages/button/tests/ButtonText.test.tsx
Closes # 
Text button component development
Adds text button component
> feat(button): text button component

- packages/button/src/ButtonPrimary.tsx
- packages/button/src/ButtonSecondary.tsx
- packages/button/src/index.ts
- packages/button/stories/SecondaryButton.stories.tsx
- packages/button/tests/ButtonSecondary.test.tsx
Closes [#462](https://vitau.atlassian.net/jira/software/projects/DSGN/boards/11?selectedIssue=DSGN-462)
Secondary button component development
Adds secondary button component
> feat(button): secondary button component

- packages/button/src/ButtonTertiary.tsx
- packages/button/src/index.ts
- packages/button/stories/TertiaryButton.stories.tsx
- packages/button/tests/ButtonTertiary.test.tsx
Closes [#462](https://vitau.atlassian.net/jira/software/projects/DSGN/boards/11?selectedIssue=DSGN-462)
Tertiary button component
> feat(button): tertiary button component

- Layerfile
Closes # 
> Deploy storybook to LayerCI
> Every PR should have a deploy to LayerCI
> Go to the checks in the PR, and enter to LayerCI details, click on View website button
> feat(storybook): config storybook deploy in prs

- .storybook/preview-head.html
- packages/button/src/ButtonBaseStyles.tsx
> feat(storybook): adding fonts

- packages/switch/package.json
- packages/switch/src/Switch.tsx
- packages/switch/src/index.ts
- packages/switch/stories/Switch.stories.tsx
- packages/switch/tests/Switch.test.tsx
- packages/switch/tests/__snapshots__/Switch.test.tsx.snap
- packages/switch/tsconfig.json
Closes [#503](https://vitau.atlassian.net/jira/software/projects/DSGN/boards/11?selectedIssue=DSGN-503)
Switch component development
> feat(switch): switch component

- packages/button/src/ButtonPrimary.tsx
- packages/button/src/ButtonSecondary.tsx
- packages/button/src/ButtonTertiary.tsx
- packages/button/stories/PrimaryButton.stories.tsx
- packages/button/stories/SecondaryButton.stories.tsx
- packages/button/stories/TertiaryButton.stories.tsx
Closes # 
> Add icon prop, as well as an iconPosition prop (left/right) in order to create a button with icon.
> ✨ feat(icons): update buttons to receive an icon component prop

- package.json
This PR updates the root package json scripts after reviewing the following articles:
- https://doppelmutzi.github.io/monorepo-lerna-yarn-workspaces/
- https://medium.com/@jsilvax/a-workflow-guide-for-lerna-with-yarn-workspaces-60f97481149d
> It seems that we had some redundant scripts running in the root package json, mainly between the `yarn` and `lerna bootstrap` scripts. According to the articles, these commands are redundant in the fact that they perform the same actions.
> This PR gives preference to the `yarn` script instead of the `lerna bootstrap`, and also removes recursive execution of scripts.
> fix: update root package json script

- packages/button/src/ButtonTertiary.tsx
- packages/button/stories/TertiaryButton.stories.tsx
Closes # 
> Add `isTransparent` prop to component button tertiary
> Tertiary Button can only have a white background and in some cases it is necessary to have transparent background.
> Tertiary Button can now have transparent background when required
> ✨ Add transparent prop to button tertiary

- CHANGELOG.md
> chore(changelog): generate changelog

- .storybook/preview.js
- packages/button/src/ButtonIcon.tsx
- packages/button/src/ButtonPrimary.tsx
- packages/button/src/ButtonSecondary.tsx
- packages/button/src/ButtonTertiary.tsx
- packages/icons/src/Icon.tsx
- packages/icons/src/createIcon.tsx
- packages/icons/tests/__snapshots__/Icon.test.tsx.snap
> Our icons where not displaying correctly inside buttons, so this PR addresses that problem and attempts to fix it by refactoring the styles.
> Icons display really tiny inside buttons in Panel
> Icons display normally
> Fix icons and button icons

- .eslintrc.js
- packages/field/package.json
- packages/field/src/Field.tsx
- packages/field/src/index.ts
- packages/field/src/useField.ts
- packages/field/stories/Field.stories.tsx
- packages/field/tests/Field.test.tsx
- packages/field/tests/__snapshots__/Field.test.tsx.snap
- packages/field/tsconfig.json
- yarn.lock
Closes [#492](https://vitau.atlassian.net/browse/DSGN-492)
> Introduces a basic field component with validation variants for success and error. Although it is still missing the helper text because it is waiting a merge of the typography package. 
> No field component
> Field component first version
> Field Component

- packages/input/package.json
- packages/input/src/Input.tsx
- packages/input/src/index.ts
- packages/input/src/useInput.ts
- packages/input/stories/Input.stories.tsx
- packages/input/tsconfig.json
> feat(input): create input package

- packages/input/src/Input.tsx
> fix(inputs): deleted flex from input component

- packages/pill/package.json
- packages/pill/src/Pill.tsx
- packages/pill/src/index.ts
- packages/pill/stories/Pill.stories.tsx
- packages/pill/tests/Pill.test.tsx
- packages/pill/tsconfig.json
Closes # 
> Adding pill component
> New components to show pill (On click event included to give functionality)
> (pill): adding pill component

- packages/typography/package.json
- packages/typography/src/Body.tsx
- packages/typography/src/Caption.tsx
- packages/typography/src/Label.tsx
- packages/typography/src/Message.tsx
- packages/typography/src/Overline.tsx
- packages/typography/src/Title.tsx
- packages/typography/src/index.ts
- packages/typography/stories/Body.stories.tsx
- packages/typography/stories/Caption.stories.tsx
- packages/typography/stories/Label.stories.tsx
- packages/typography/stories/Message.stories.tsx
- packages/typography/stories/Overline.stories.tsx
- packages/typography/stories/Title.stories.tsx
- packages/typography/tests/Typography.test.tsx
- packages/typography/tsconfig.json
- yarn.lock
> feat(typography): adding typography

- .storybook/preview-head.html
- package.json
- packages/select/package.json
- packages/select/src/Select.tsx
- packages/select/src/index.ts
- packages/select/stories/Select.stories.tsx
- packages/select/tests/Select.test.tsx
- packages/select/tsconfig.json
- yarn.lock
> (select): adding select component

- packages/input/src/Input.tsx
- packages/typography/src/Caption.tsx
- packages/typography/src/Label.tsx
- packages/typography/src/Overline.tsx
- packages/typography/src/Title.tsx
- packages/typography/stories/Body.stories.tsx
> fix(typography): fixes from design QA

- package.json
- packages/select/src/Select.tsx
- packages/select/src/useSelect.ts
- packages/select/stories/Select.stories.tsx
> feat(select): change select design

- CONTRIBUTING.md
- README.md
Closes # 453
> Added contribution guidelines and update readme.md
It is a proposal to standardize the naming of branches and commits in addition to define the pull request process
> feat(guidelines): readme and contribution documentation updates

- packages/loader/package.json
- packages/loader/src/Loader.tsx
- packages/loader/src/index.ts
- packages/loader/stories/Loader.stories.tsx
- packages/loader/tsconfig.json
> feat(loader): create loader package

- packages/input/src/Input.tsx
- packages/input/stories/Input.stories.tsx
Closes #537
Fixing hover styles.
- The hover style should don't exist
- Added password input example
> feat: fix input stories

- packages/iconButton/src/ButtonBaseStyles.tsx
- packages/iconButton/src/IconButton.tsx
- packages/iconButton/src/index.ts
- packages/iconButton/src/useIconButton.ts
- packages/iconButton/stories/IconButton.stories.tsx
> Rulo/dsgn 537/icon button

- .storybook/tokens.css
- packages/button/src/ButtonBaseStyles.tsx
- packages/button/src/ButtonPrimary.tsx
- packages/button/src/ButtonSecondary.tsx
- packages/button/src/ButtonTertiary.tsx
- packages/button/src/ButtonText.tsx
- packages/field/src/Field.tsx
- packages/iconButton/src/ButtonBaseStyles.tsx
- packages/iconButton/src/IconButton.tsx
- packages/input/src/Input.tsx
- packages/loader/src/Loader.tsx
- packages/pill/src/Pill.tsx
- tokens.ts
> feat(input): using design tokens

- packages/button/src/ButtonPrimary.tsx
Closes # 
adding global styles to button font
> feat(button): adding global token

- packages/input/src/Input.tsx
> feat(input): adding tokens

- packages/button/src/ButtonPrimary.tsx
- packages/button/src/ButtonSecondary.tsx
- packages/button/src/ButtonTertiary.tsx
- packages/button/stories/PrimaryButton.stories.tsx
> feat(button): adding loading
